/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETAccountAccountIdLists200ResultsItemPosterPath } from './gETAccountAccountIdLists200ResultsItemPosterPath';

export type GETAccountAccountIdLists200ResultsItem = {
  description?: string;
  favorite_count?: number;
  id?: number;
  item_count?: number;
  iso_639_1?: string;
  list_type?: string;
  name?: string;
  poster_path?: GETAccountAccountIdLists200ResultsItemPosterPath;
};
