/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETCreditCreditId200Media } from './gETCreditCreditId200Media';
import type { GETCreditCreditId200Person } from './gETCreditCreditId200Person';

export type GETCreditCreditId200 = {
  credit_type?: string;
  department?: string;
  job?: string;
  media?: GETCreditCreditId200Media;
  media_type?: string;
  id?: string;
  person?: GETCreditCreditId200Person;
};
