/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETCertificationMovieList200CertificationsUsItem } from './gETCertificationMovieList200CertificationsUsItem';
import type { GETCertificationMovieList200CertificationsCaItem } from './gETCertificationMovieList200CertificationsCaItem';
import type { GETCertificationMovieList200CertificationsDeItem } from './gETCertificationMovieList200CertificationsDeItem';
import type { GETCertificationMovieList200CertificationsGbItem } from './gETCertificationMovieList200CertificationsGbItem';
import type { GETCertificationMovieList200CertificationsAuItem } from './gETCertificationMovieList200CertificationsAuItem';
import type { GETCertificationMovieList200CertificationsBrItem } from './gETCertificationMovieList200CertificationsBrItem';
import type { GETCertificationMovieList200CertificationsFrItem } from './gETCertificationMovieList200CertificationsFrItem';
import type { GETCertificationMovieList200CertificationsNzItem } from './gETCertificationMovieList200CertificationsNzItem';
import type { GETCertificationMovieList200CertificationsInItem } from './gETCertificationMovieList200CertificationsInItem';

export type GETCertificationMovieList200Certifications = {
  US?: GETCertificationMovieList200CertificationsUsItem[];
  CA?: GETCertificationMovieList200CertificationsCaItem[];
  DE?: GETCertificationMovieList200CertificationsDeItem[];
  GB?: GETCertificationMovieList200CertificationsGbItem[];
  AU?: GETCertificationMovieList200CertificationsAuItem[];
  BR?: GETCertificationMovieList200CertificationsBrItem[];
  FR?: GETCertificationMovieList200CertificationsFrItem[];
  NZ?: GETCertificationMovieList200CertificationsNzItem[];
  IN?: GETCertificationMovieList200CertificationsInItem[];
};
