/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETCollectionCollectionIdImages200BackdropsItemIso6391 } from './gETCollectionCollectionIdImages200BackdropsItemIso6391';

export type GETCollectionCollectionIdImages200BackdropsItem = {
  aspect_ratio?: number;
  file_path?: string;
  height?: number;
  iso_639_1?: GETCollectionCollectionIdImages200BackdropsItemIso6391;
  vote_average?: number;
  vote_count?: number;
  width?: number;
};
