/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETCollectionCollectionId200PartsItemBackdropPath } from './gETCollectionCollectionId200PartsItemBackdropPath';

export type GETCollectionCollectionId200PartsItem = {
  adult?: boolean;
  backdrop_path?: GETCollectionCollectionId200PartsItemBackdropPath;
  genre_ids?: number[];
  id?: number;
  original_language?: string;
  original_title?: string;
  overview?: string;
  release_date?: string;
  poster_path?: string;
  popularity?: number;
  title?: string;
  video?: boolean;
  vote_average?: number;
  vote_count?: number;
};
