/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETCompanyCompanyId200ParentCompany } from './gETCompanyCompanyId200ParentCompany';

export type GETCompanyCompanyId200 = {
  description?: string;
  headquarters?: string;
  homepage?: string;
  id?: number;
  logo_path?: string;
  name?: string;
  origin_country?: string;
  parent_company?: GETCompanyCompanyId200ParentCompany;
};
