/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETCollectionCollectionId200PosterPath } from './gETCollectionCollectionId200PosterPath';
import type { GETCollectionCollectionId200PartsItem } from './gETCollectionCollectionId200PartsItem';

export type GETCollectionCollectionId200 = {
  id?: number;
  name?: string;
  overview?: string;
  poster_path?: GETCollectionCollectionId200PosterPath;
  backdrop_path?: string;
  parts?: GETCollectionCollectionId200PartsItem[];
};
