/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */

export type GETCompanyCompanyIdImages200LogosItemFileType = '.svg' | '.png';

export const GETCompanyCompanyIdImages200LogosItemFileType = {
  svg: '.svg' as GETCompanyCompanyIdImages200LogosItemFileType,
  png: '.png' as GETCompanyCompanyIdImages200LogosItemFileType,
};
