/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */

export type GETDiscoverTvSortBy =
  | ''
  | 'vote_average.desc'
  | 'vote_average.asc'
  | 'first_air_date.desc'
  | 'first_air_date.asc'
  | 'popularity.desc'
  | 'popularity.asc';

export const GETDiscoverTvSortBy = {
  NUMBER_: '' as GETDiscoverTvSortBy,
  vote_averagedesc: 'vote_average.desc' as GETDiscoverTvSortBy,
  vote_averageasc: 'vote_average.asc' as GETDiscoverTvSortBy,
  first_air_datedesc: 'first_air_date.desc' as GETDiscoverTvSortBy,
  first_air_dateasc: 'first_air_date.asc' as GETDiscoverTvSortBy,
  popularitydesc: 'popularity.desc' as GETDiscoverTvSortBy,
  popularityasc: 'popularity.asc' as GETDiscoverTvSortBy,
};
