/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { MovieListObject } from './movieListObject';
import type { PersonListResultsObject } from './personListResultsObject';
import type { TvListResultObject } from './tvListResultObject';
import type { GETFindExternalId200TvEpisodeResultsItem } from './gETFindExternalId200TvEpisodeResultsItem';
import type { GETFindExternalId200TvSeasonResultsItem } from './gETFindExternalId200TvSeasonResultsItem';

export type GETFindExternalId200 = {
  movie_results?: MovieListObject[];
  person_results?: PersonListResultsObject[];
  tv_results?: TvListResultObject[];
  tv_episode_results?: GETFindExternalId200TvEpisodeResultsItem[];
  tv_season_results?: GETFindExternalId200TvSeasonResultsItem[];
};
