/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { MovieListObject } from './movieListObject';
import type { ImagePath } from './imagePath';

export type GETListListId200 = {
  created_by?: string;
  description?: string;
  favorite_count?: number;
  id?: string;
  items?: MovieListObject[];
  item_count?: number;
  iso_639_1?: string;
  name?: string;
  poster_path?: ImagePath;
};
