/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsAtRentItem } from './gETMovieMovieIdWatchProviders200ResultsAtRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsAtBuyItem } from './gETMovieMovieIdWatchProviders200ResultsAtBuyItem';

export type GETMovieMovieIdWatchProviders200ResultsAt = {
  link?: string;
  rent?: GETMovieMovieIdWatchProviders200ResultsAtRentItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsAtBuyItem[];
};
