/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsGbRentItem } from './gETMovieMovieIdWatchProviders200ResultsGbRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsGbFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsGbFlatrateItem';
import type { GETMovieMovieIdWatchProviders200ResultsGbBuyItem } from './gETMovieMovieIdWatchProviders200ResultsGbBuyItem';

export type GETMovieMovieIdWatchProviders200ResultsGb = {
  link?: string;
  rent?: GETMovieMovieIdWatchProviders200ResultsGbRentItem[];
  flatrate?: GETMovieMovieIdWatchProviders200ResultsGbFlatrateItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsGbBuyItem[];
};
