/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsAr } from './gETMovieMovieIdWatchProviders200ResultsAr';
import type { GETMovieMovieIdWatchProviders200ResultsAt } from './gETMovieMovieIdWatchProviders200ResultsAt';
import type { GETMovieMovieIdWatchProviders200ResultsAu } from './gETMovieMovieIdWatchProviders200ResultsAu';
import type { GETMovieMovieIdWatchProviders200ResultsBe } from './gETMovieMovieIdWatchProviders200ResultsBe';
import type { GETMovieMovieIdWatchProviders200ResultsBr } from './gETMovieMovieIdWatchProviders200ResultsBr';
import type { GETMovieMovieIdWatchProviders200ResultsCa } from './gETMovieMovieIdWatchProviders200ResultsCa';
import type { GETMovieMovieIdWatchProviders200ResultsCh } from './gETMovieMovieIdWatchProviders200ResultsCh';
import type { GETMovieMovieIdWatchProviders200ResultsCl } from './gETMovieMovieIdWatchProviders200ResultsCl';
import type { GETMovieMovieIdWatchProviders200ResultsCo } from './gETMovieMovieIdWatchProviders200ResultsCo';
import type { GETMovieMovieIdWatchProviders200ResultsCz } from './gETMovieMovieIdWatchProviders200ResultsCz';
import type { GETMovieMovieIdWatchProviders200ResultsDe } from './gETMovieMovieIdWatchProviders200ResultsDe';
import type { GETMovieMovieIdWatchProviders200ResultsDk } from './gETMovieMovieIdWatchProviders200ResultsDk';
import type { GETMovieMovieIdWatchProviders200ResultsEc } from './gETMovieMovieIdWatchProviders200ResultsEc';
import type { GETMovieMovieIdWatchProviders200ResultsEe } from './gETMovieMovieIdWatchProviders200ResultsEe';
import type { GETMovieMovieIdWatchProviders200ResultsEs } from './gETMovieMovieIdWatchProviders200ResultsEs';
import type { GETMovieMovieIdWatchProviders200ResultsFi } from './gETMovieMovieIdWatchProviders200ResultsFi';
import type { GETMovieMovieIdWatchProviders200ResultsFr } from './gETMovieMovieIdWatchProviders200ResultsFr';
import type { GETMovieMovieIdWatchProviders200ResultsGb } from './gETMovieMovieIdWatchProviders200ResultsGb';
import type { GETMovieMovieIdWatchProviders200ResultsGr } from './gETMovieMovieIdWatchProviders200ResultsGr';
import type { GETMovieMovieIdWatchProviders200ResultsHu } from './gETMovieMovieIdWatchProviders200ResultsHu';
import type { GETMovieMovieIdWatchProviders200ResultsId } from './gETMovieMovieIdWatchProviders200ResultsId';
import type { GETMovieMovieIdWatchProviders200ResultsIe } from './gETMovieMovieIdWatchProviders200ResultsIe';
import type { GETMovieMovieIdWatchProviders200ResultsIn } from './gETMovieMovieIdWatchProviders200ResultsIn';
import type { GETMovieMovieIdWatchProviders200ResultsIt } from './gETMovieMovieIdWatchProviders200ResultsIt';
import type { GETMovieMovieIdWatchProviders200ResultsJp } from './gETMovieMovieIdWatchProviders200ResultsJp';
import type { GETMovieMovieIdWatchProviders200ResultsKr } from './gETMovieMovieIdWatchProviders200ResultsKr';
import type { GETMovieMovieIdWatchProviders200ResultsLt } from './gETMovieMovieIdWatchProviders200ResultsLt';
import type { GETMovieMovieIdWatchProviders200ResultsLv } from './gETMovieMovieIdWatchProviders200ResultsLv';
import type { GETMovieMovieIdWatchProviders200ResultsMx } from './gETMovieMovieIdWatchProviders200ResultsMx';
import type { GETMovieMovieIdWatchProviders200ResultsMy } from './gETMovieMovieIdWatchProviders200ResultsMy';
import type { GETMovieMovieIdWatchProviders200ResultsNl } from './gETMovieMovieIdWatchProviders200ResultsNl';
import type { GETMovieMovieIdWatchProviders200ResultsNo } from './gETMovieMovieIdWatchProviders200ResultsNo';
import type { GETMovieMovieIdWatchProviders200ResultsNz } from './gETMovieMovieIdWatchProviders200ResultsNz';
import type { GETMovieMovieIdWatchProviders200ResultsPe } from './gETMovieMovieIdWatchProviders200ResultsPe';
import type { GETMovieMovieIdWatchProviders200ResultsPh } from './gETMovieMovieIdWatchProviders200ResultsPh';
import type { GETMovieMovieIdWatchProviders200ResultsPl } from './gETMovieMovieIdWatchProviders200ResultsPl';
import type { GETMovieMovieIdWatchProviders200ResultsPt } from './gETMovieMovieIdWatchProviders200ResultsPt';
import type { GETMovieMovieIdWatchProviders200ResultsRo } from './gETMovieMovieIdWatchProviders200ResultsRo';
import type { GETMovieMovieIdWatchProviders200ResultsRu } from './gETMovieMovieIdWatchProviders200ResultsRu';
import type { GETMovieMovieIdWatchProviders200ResultsSe } from './gETMovieMovieIdWatchProviders200ResultsSe';
import type { GETMovieMovieIdWatchProviders200ResultsSg } from './gETMovieMovieIdWatchProviders200ResultsSg';
import type { GETMovieMovieIdWatchProviders200ResultsTh } from './gETMovieMovieIdWatchProviders200ResultsTh';
import type { GETMovieMovieIdWatchProviders200ResultsTr } from './gETMovieMovieIdWatchProviders200ResultsTr';
import type { GETMovieMovieIdWatchProviders200ResultsUs } from './gETMovieMovieIdWatchProviders200ResultsUs';
import type { GETMovieMovieIdWatchProviders200ResultsVe } from './gETMovieMovieIdWatchProviders200ResultsVe';
import type { GETMovieMovieIdWatchProviders200ResultsZa } from './gETMovieMovieIdWatchProviders200ResultsZa';

export type GETMovieMovieIdWatchProviders200Results = {
  AR?: GETMovieMovieIdWatchProviders200ResultsAr;
  AT?: GETMovieMovieIdWatchProviders200ResultsAt;
  AU?: GETMovieMovieIdWatchProviders200ResultsAu;
  BE?: GETMovieMovieIdWatchProviders200ResultsBe;
  BR?: GETMovieMovieIdWatchProviders200ResultsBr;
  CA?: GETMovieMovieIdWatchProviders200ResultsCa;
  CH?: GETMovieMovieIdWatchProviders200ResultsCh;
  CL?: GETMovieMovieIdWatchProviders200ResultsCl;
  CO?: GETMovieMovieIdWatchProviders200ResultsCo;
  CZ?: GETMovieMovieIdWatchProviders200ResultsCz;
  DE?: GETMovieMovieIdWatchProviders200ResultsDe;
  DK?: GETMovieMovieIdWatchProviders200ResultsDk;
  EC?: GETMovieMovieIdWatchProviders200ResultsEc;
  EE?: GETMovieMovieIdWatchProviders200ResultsEe;
  ES?: GETMovieMovieIdWatchProviders200ResultsEs;
  FI?: GETMovieMovieIdWatchProviders200ResultsFi;
  FR?: GETMovieMovieIdWatchProviders200ResultsFr;
  GB?: GETMovieMovieIdWatchProviders200ResultsGb;
  GR?: GETMovieMovieIdWatchProviders200ResultsGr;
  HU?: GETMovieMovieIdWatchProviders200ResultsHu;
  ID?: GETMovieMovieIdWatchProviders200ResultsId;
  IE?: GETMovieMovieIdWatchProviders200ResultsIe;
  IN?: GETMovieMovieIdWatchProviders200ResultsIn;
  IT?: GETMovieMovieIdWatchProviders200ResultsIt;
  JP?: GETMovieMovieIdWatchProviders200ResultsJp;
  KR?: GETMovieMovieIdWatchProviders200ResultsKr;
  LT?: GETMovieMovieIdWatchProviders200ResultsLt;
  LV?: GETMovieMovieIdWatchProviders200ResultsLv;
  MX?: GETMovieMovieIdWatchProviders200ResultsMx;
  MY?: GETMovieMovieIdWatchProviders200ResultsMy;
  NL?: GETMovieMovieIdWatchProviders200ResultsNl;
  NO?: GETMovieMovieIdWatchProviders200ResultsNo;
  NZ?: GETMovieMovieIdWatchProviders200ResultsNz;
  PE?: GETMovieMovieIdWatchProviders200ResultsPe;
  PH?: GETMovieMovieIdWatchProviders200ResultsPh;
  PL?: GETMovieMovieIdWatchProviders200ResultsPl;
  PT?: GETMovieMovieIdWatchProviders200ResultsPt;
  RO?: GETMovieMovieIdWatchProviders200ResultsRo;
  RU?: GETMovieMovieIdWatchProviders200ResultsRu;
  SE?: GETMovieMovieIdWatchProviders200ResultsSe;
  SG?: GETMovieMovieIdWatchProviders200ResultsSg;
  TH?: GETMovieMovieIdWatchProviders200ResultsTh;
  TR?: GETMovieMovieIdWatchProviders200ResultsTr;
  US?: GETMovieMovieIdWatchProviders200ResultsUs;
  VE?: GETMovieMovieIdWatchProviders200ResultsVe;
  ZA?: GETMovieMovieIdWatchProviders200ResultsZa;
};
