/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsNlFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsNlFlatrateItem';
import type { GETMovieMovieIdWatchProviders200ResultsNlBuyItem } from './gETMovieMovieIdWatchProviders200ResultsNlBuyItem';
import type { GETMovieMovieIdWatchProviders200ResultsNlRentItem } from './gETMovieMovieIdWatchProviders200ResultsNlRentItem';

export type GETMovieMovieIdWatchProviders200ResultsNl = {
  link?: string;
  flatrate?: GETMovieMovieIdWatchProviders200ResultsNlFlatrateItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsNlBuyItem[];
  rent?: GETMovieMovieIdWatchProviders200ResultsNlRentItem[];
};
