/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsSeRentItem } from './gETMovieMovieIdWatchProviders200ResultsSeRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsSeFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsSeFlatrateItem';
import type { GETMovieMovieIdWatchProviders200ResultsSeBuyItem } from './gETMovieMovieIdWatchProviders200ResultsSeBuyItem';

export type GETMovieMovieIdWatchProviders200ResultsSe = {
  link?: string;
  rent?: GETMovieMovieIdWatchProviders200ResultsSeRentItem[];
  flatrate?: GETMovieMovieIdWatchProviders200ResultsSeFlatrateItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsSeBuyItem[];
};
