/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdReleaseDates200ResultsItemReleaseDatesItem } from './gETMovieMovieIdReleaseDates200ResultsItemReleaseDatesItem';

export type GETMovieMovieIdReleaseDates200ResultsItem = {
  iso_3166_1?: string;
  release_dates?: GETMovieMovieIdReleaseDates200ResultsItemReleaseDatesItem[];
};
