/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsClFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsClFlatrateItem';
import type { GETMovieMovieIdWatchProviders200ResultsClBuyItem } from './gETMovieMovieIdWatchProviders200ResultsClBuyItem';
import type { GETMovieMovieIdWatchProviders200ResultsClRentItem } from './gETMovieMovieIdWatchProviders200ResultsClRentItem';

export type GETMovieMovieIdWatchProviders200ResultsCl = {
  link?: string;
  flatrate?: GETMovieMovieIdWatchProviders200ResultsClFlatrateItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsClBuyItem[];
  rent?: GETMovieMovieIdWatchProviders200ResultsClRentItem[];
};
