/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */

export type GETMovieMovieId200Status =
  | 'Rumored'
  | 'Planned'
  | 'In Production'
  | 'Post Production'
  | 'Released'
  | 'Canceled';

export const GETMovieMovieId200Status = {
  Rumored: 'Rumored' as GETMovieMovieId200Status,
  Planned: 'Planned' as GETMovieMovieId200Status,
  In_Production: 'In Production' as GETMovieMovieId200Status,
  Post_Production: 'Post Production' as GETMovieMovieId200Status,
  Released: 'Released' as GETMovieMovieId200Status,
  Canceled: 'Canceled' as GETMovieMovieId200Status,
};
