/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsPtRentItem } from './gETMovieMovieIdWatchProviders200ResultsPtRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsPtFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsPtFlatrateItem';
import type { GETMovieMovieIdWatchProviders200ResultsPtBuyItem } from './gETMovieMovieIdWatchProviders200ResultsPtBuyItem';

export type GETMovieMovieIdWatchProviders200ResultsPt = {
  link?: string;
  rent?: GETMovieMovieIdWatchProviders200ResultsPtRentItem[];
  flatrate?: GETMovieMovieIdWatchProviders200ResultsPtFlatrateItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsPtBuyItem[];
};
