/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsAuRentItem } from './gETMovieMovieIdWatchProviders200ResultsAuRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsAuBuyItem } from './gETMovieMovieIdWatchProviders200ResultsAuBuyItem';
import type { GETMovieMovieIdWatchProviders200ResultsAuFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsAuFlatrateItem';

export type GETMovieMovieIdWatchProviders200ResultsAu = {
  link?: string;
  rent?: GETMovieMovieIdWatchProviders200ResultsAuRentItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsAuBuyItem[];
  flatrate?: GETMovieMovieIdWatchProviders200ResultsAuFlatrateItem[];
};
