/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsZaRentItem } from './gETMovieMovieIdWatchProviders200ResultsZaRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsZaBuyItem } from './gETMovieMovieIdWatchProviders200ResultsZaBuyItem';
import type { GETMovieMovieIdWatchProviders200ResultsZaFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsZaFlatrateItem';

export type GETMovieMovieIdWatchProviders200ResultsZa = {
  link?: string;
  rent?: GETMovieMovieIdWatchProviders200ResultsZaRentItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsZaBuyItem[];
  flatrate?: GETMovieMovieIdWatchProviders200ResultsZaFlatrateItem[];
};
