/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsItBuyItem } from './gETMovieMovieIdWatchProviders200ResultsItBuyItem';
import type { GETMovieMovieIdWatchProviders200ResultsItFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsItFlatrateItem';
import type { GETMovieMovieIdWatchProviders200ResultsItRentItem } from './gETMovieMovieIdWatchProviders200ResultsItRentItem';

export type GETMovieMovieIdWatchProviders200ResultsIt = {
  link?: string;
  buy?: GETMovieMovieIdWatchProviders200ResultsItBuyItem[];
  flatrate?: GETMovieMovieIdWatchProviders200ResultsItFlatrateItem[];
  rent?: GETMovieMovieIdWatchProviders200ResultsItRentItem[];
};
