/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdImages200BackdropsItem } from './gETMovieMovieIdImages200BackdropsItem';
import type { GETMovieMovieIdImages200PostersItem } from './gETMovieMovieIdImages200PostersItem';

export type GETMovieMovieIdImages200 = {
  id?: number;
  backdrops?: GETMovieMovieIdImages200BackdropsItem[];
  posters?: GETMovieMovieIdImages200PostersItem[];
};
