/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsCoFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsCoFlatrateItem';
import type { GETMovieMovieIdWatchProviders200ResultsCoRentItem } from './gETMovieMovieIdWatchProviders200ResultsCoRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsCoBuyItem } from './gETMovieMovieIdWatchProviders200ResultsCoBuyItem';

export type GETMovieMovieIdWatchProviders200ResultsCo = {
  link?: string;
  flatrate?: GETMovieMovieIdWatchProviders200ResultsCoFlatrateItem[];
  rent?: GETMovieMovieIdWatchProviders200ResultsCoRentItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsCoBuyItem[];
};
