/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsTrBuyItem } from './gETMovieMovieIdWatchProviders200ResultsTrBuyItem';
import type { GETMovieMovieIdWatchProviders200ResultsTrRentItem } from './gETMovieMovieIdWatchProviders200ResultsTrRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsTrFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsTrFlatrateItem';

export type GETMovieMovieIdWatchProviders200ResultsTr = {
  link?: string;
  buy?: GETMovieMovieIdWatchProviders200ResultsTrBuyItem[];
  rent?: GETMovieMovieIdWatchProviders200ResultsTrRentItem[];
  flatrate?: GETMovieMovieIdWatchProviders200ResultsTrFlatrateItem[];
};
