/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsPeFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsPeFlatrateItem';
import type { GETMovieMovieIdWatchProviders200ResultsPeRentItem } from './gETMovieMovieIdWatchProviders200ResultsPeRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsPeBuyItem } from './gETMovieMovieIdWatchProviders200ResultsPeBuyItem';

export type GETMovieMovieIdWatchProviders200ResultsPe = {
  link?: string;
  flatrate?: GETMovieMovieIdWatchProviders200ResultsPeFlatrateItem[];
  rent?: GETMovieMovieIdWatchProviders200ResultsPeRentItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsPeBuyItem[];
};
