/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsNoBuyItem } from './gETMovieMovieIdWatchProviders200ResultsNoBuyItem';
import type { GETMovieMovieIdWatchProviders200ResultsNoRentItem } from './gETMovieMovieIdWatchProviders200ResultsNoRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsNoFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsNoFlatrateItem';

export type GETMovieMovieIdWatchProviders200ResultsNo = {
  link?: string;
  buy?: GETMovieMovieIdWatchProviders200ResultsNoBuyItem[];
  rent?: GETMovieMovieIdWatchProviders200ResultsNoRentItem[];
  flatrate?: GETMovieMovieIdWatchProviders200ResultsNoFlatrateItem[];
};
