/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsIdFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsIdFlatrateItem';
import type { GETMovieMovieIdWatchProviders200ResultsIdRentItem } from './gETMovieMovieIdWatchProviders200ResultsIdRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsIdBuyItem } from './gETMovieMovieIdWatchProviders200ResultsIdBuyItem';

export type GETMovieMovieIdWatchProviders200ResultsId = {
  link?: string;
  flatrate?: GETMovieMovieIdWatchProviders200ResultsIdFlatrateItem[];
  rent?: GETMovieMovieIdWatchProviders200ResultsIdRentItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsIdBuyItem[];
};
