/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsPhRentItem } from './gETMovieMovieIdWatchProviders200ResultsPhRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsPhBuyItem } from './gETMovieMovieIdWatchProviders200ResultsPhBuyItem';
import type { GETMovieMovieIdWatchProviders200ResultsPhFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsPhFlatrateItem';

export type GETMovieMovieIdWatchProviders200ResultsPh = {
  link?: string;
  rent?: GETMovieMovieIdWatchProviders200ResultsPhRentItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsPhBuyItem[];
  flatrate?: GETMovieMovieIdWatchProviders200ResultsPhFlatrateItem[];
};
