/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsChRentItem } from './gETMovieMovieIdWatchProviders200ResultsChRentItem';
import type { GETMovieMovieIdWatchProviders200ResultsChBuyItem } from './gETMovieMovieIdWatchProviders200ResultsChBuyItem';
import type { GETMovieMovieIdWatchProviders200ResultsChFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsChFlatrateItem';

export type GETMovieMovieIdWatchProviders200ResultsCh = {
  link?: string;
  rent?: GETMovieMovieIdWatchProviders200ResultsChRentItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsChBuyItem[];
  flatrate?: GETMovieMovieIdWatchProviders200ResultsChFlatrateItem[];
};
