/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETMovieMovieIdWatchProviders200ResultsSgFlatrateItem } from './gETMovieMovieIdWatchProviders200ResultsSgFlatrateItem';
import type { GETMovieMovieIdWatchProviders200ResultsSgBuyItem } from './gETMovieMovieIdWatchProviders200ResultsSgBuyItem';
import type { GETMovieMovieIdWatchProviders200ResultsSgRentItem } from './gETMovieMovieIdWatchProviders200ResultsSgRentItem';

export type GETMovieMovieIdWatchProviders200ResultsSg = {
  link?: string;
  flatrate?: GETMovieMovieIdWatchProviders200ResultsSgFlatrateItem[];
  buy?: GETMovieMovieIdWatchProviders200ResultsSgBuyItem[];
  rent?: GETMovieMovieIdWatchProviders200ResultsSgRentItem[];
};
