/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETNetworkNetworkIdImages200LogosItemFileType } from './gETNetworkNetworkIdImages200LogosItemFileType';

export type GETNetworkNetworkIdImages200LogosItem = {
  aspect_ratio?: number;
  file_path?: string;
  height?: number;
  id?: string;
  file_type?: GETNetworkNetworkIdImages200LogosItemFileType;
  vote_average?: number;
  vote_count?: number;
  width?: number;
};
