/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETPersonPersonIdMovieCredits200CastItem } from './gETPersonPersonIdMovieCredits200CastItem';
import type { GETPersonPersonIdMovieCredits200CrewItem } from './gETPersonPersonIdMovieCredits200CrewItem';

export type GETPersonPersonIdMovieCredits200 = {
  cast?: GETPersonPersonIdMovieCredits200CastItem[];
  crew?: GETPersonPersonIdMovieCredits200CrewItem[];
  id?: number;
};
