/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETPersonPopular200ResultsItemKnownForItem } from './gETPersonPopular200ResultsItemKnownForItem';

export type GETPersonPopular200ResultsItem = {
  profile_path?: string;
  adult?: boolean;
  id?: number;
  known_for?: GETPersonPopular200ResultsItemKnownForItem[];
  name?: string;
  popularity?: number;
};
