/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETPersonPersonIdMovieCredits200CastItemVoteAverage } from './gETPersonPersonIdMovieCredits200CastItemVoteAverage';
import type { ImagePath } from './imagePath';

export type GETPersonPersonIdMovieCredits200CastItem = {
  character?: string;
  credit_id?: string;
  release_date?: string;
  vote_count?: number;
  video?: boolean;
  adult?: boolean;
  vote_average?: GETPersonPersonIdMovieCredits200CastItemVoteAverage;
  title?: string;
  genre_ids?: number[];
  original_language?: string;
  original_title?: string;
  popularity?: number;
  id?: number;
  backdrop_path?: ImagePath;
  overview?: string;
  poster_path?: ImagePath;
};
