/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETPersonLatest200AlsoKnownAsItem } from './gETPersonLatest200AlsoKnownAsItem';
import type { ImagePath } from './imagePath';

export type GETPersonLatest200 = {
  adult?: boolean;
  also_known_as?: GETPersonLatest200AlsoKnownAsItem[];
  biography?: string | null;
  birthday?: string | null;
  deathday?: string | null;
  gender?: number;
  homepage?: string | null;
  id?: number;
  imdb_id?: string | null;
  name?: string;
  place_of_birth?: string | null;
  popularity?: number;
  profile_path?: ImagePath;
};
