/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { ImagePath } from './imagePath';

export type GETPersonPersonIdTvCredits200CastItem = {
  credit_id?: string;
  original_name?: string;
  id?: number;
  genre_ids?: number[];
  character?: string;
  name?: string;
  poster_path?: ImagePath;
  vote_count?: number;
  vote_average?: number;
  popularity?: number;
  episode_count?: number;
  original_language?: string;
  first_air_date?: string;
  backdrop_path?: ImagePath;
  overview?: string;
  origin_country?: string[];
};
