/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETPersonPersonIdTaggedImages200ResultsItemMedia } from './gETPersonPersonIdTaggedImages200ResultsItemMedia';

export type GETPersonPersonIdTaggedImages200ResultsItem = {
  aspect_ratio?: number;
  file_path?: string;
  height?: number;
  id?: string;
  iso_639_1?: string | null;
  vote_average?: number;
  vote_count?: number;
  width?: number;
  image_type?: string;
  media?: GETPersonPersonIdTaggedImages200ResultsItemMedia;
  media_type?: string;
};
