/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETPersonPersonIdCombinedCredits200CastItem } from './gETPersonPersonIdCombinedCredits200CastItem';
import type { GETPersonPersonIdCombinedCredits200CrewItem } from './gETPersonPersonIdCombinedCredits200CrewItem';

export type GETPersonPersonIdCombinedCredits200 = {
  cast?: GETPersonPersonIdCombinedCredits200CastItem[];
  crew?: GETPersonPersonIdCombinedCredits200CrewItem[];
  id?: number;
};
