/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdWatchProviders200ResultsJpRentItem } from './gETTvTvIdWatchProviders200ResultsJpRentItem';
import type { GETTvTvIdWatchProviders200ResultsJpFlatrateItem } from './gETTvTvIdWatchProviders200ResultsJpFlatrateItem';
import type { GETTvTvIdWatchProviders200ResultsJpBuyItem } from './gETTvTvIdWatchProviders200ResultsJpBuyItem';

export type GETTvTvIdWatchProviders200ResultsJp = {
  link?: string;
  rent?: GETTvTvIdWatchProviders200ResultsJpRentItem[];
  flatrate?: GETTvTvIdWatchProviders200ResultsJpFlatrateItem[];
  buy?: GETTvTvIdWatchProviders200ResultsJpBuyItem[];
};
