/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdWatchProviders200ResultsPlFlatrateItem } from './gETTvTvIdWatchProviders200ResultsPlFlatrateItem';
import type { GETTvTvIdWatchProviders200ResultsPlAdsItem } from './gETTvTvIdWatchProviders200ResultsPlAdsItem';

export type GETTvTvIdWatchProviders200ResultsPl = {
  link?: string;
  flatrate?: GETTvTvIdWatchProviders200ResultsPlFlatrateItem[];
  ads?: GETTvTvIdWatchProviders200ResultsPlAdsItem[];
};
