/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdTranslations200TranslationsItemData } from './gETTvTvIdTranslations200TranslationsItemData';

export type GETTvTvIdTranslations200TranslationsItem = {
  iso_3166_1?: string;
  iso_639_1?: string;
  name?: string;
  english_name?: string;
  data?: GETTvTvIdTranslations200TranslationsItemData;
};
