/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdAggregateCredits200CastItem } from './gETTvTvIdAggregateCredits200CastItem';
import type { GETTvTvIdAggregateCredits200CrewItem } from './gETTvTvIdAggregateCredits200CrewItem';

export type GETTvTvIdAggregateCredits200 = {
  cast?: GETTvTvIdAggregateCredits200CastItem[];
  crew?: GETTvTvIdAggregateCredits200CrewItem[];
  id?: number;
};
