/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdWatchProviders200ResultsIeBuyItem } from './gETTvTvIdWatchProviders200ResultsIeBuyItem';
import type { GETTvTvIdWatchProviders200ResultsIeFlatrateItem } from './gETTvTvIdWatchProviders200ResultsIeFlatrateItem';

export type GETTvTvIdWatchProviders200ResultsIe = {
  link?: string;
  buy?: GETTvTvIdWatchProviders200ResultsIeBuyItem[];
  flatrate?: GETTvTvIdWatchProviders200ResultsIeFlatrateItem[];
};
