/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCredits200CastItem } from './gETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCredits200CastItem';
import type { GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCredits200CrewItem } from './gETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCredits200CrewItem';
import type { GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCredits200GuestStarsItem } from './gETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCredits200GuestStarsItem';

export type GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCredits200 = {
  cast?: GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCredits200CastItem[];
  crew?: GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCredits200CrewItem[];
  guest_stars?: GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCredits200GuestStarsItem[];
  id?: number;
};
