/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdWatchProviders200ResultsAtBuyItem } from './gETTvTvIdWatchProviders200ResultsAtBuyItem';
import type { GETTvTvIdWatchProviders200ResultsAtFlatrateItem } from './gETTvTvIdWatchProviders200ResultsAtFlatrateItem';

export type GETTvTvIdWatchProviders200ResultsAt = {
  link?: string;
  buy?: GETTvTvIdWatchProviders200ResultsAtBuyItem[];
  flatrate?: GETTvTvIdWatchProviders200ResultsAtFlatrateItem[];
};
