/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdWatchProviders200ResultsNoBuyItem } from './gETTvTvIdWatchProviders200ResultsNoBuyItem';
import type { GETTvTvIdWatchProviders200ResultsNoFlatrateItem } from './gETTvTvIdWatchProviders200ResultsNoFlatrateItem';

export type GETTvTvIdWatchProviders200ResultsNo = {
  link?: string;
  buy?: GETTvTvIdWatchProviders200ResultsNoBuyItem[];
  flatrate?: GETTvTvIdWatchProviders200ResultsNoFlatrateItem[];
};
