/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdWatchProviders200ResultsGbFlatrateItem } from './gETTvTvIdWatchProviders200ResultsGbFlatrateItem';
import type { GETTvTvIdWatchProviders200ResultsGbBuyItem } from './gETTvTvIdWatchProviders200ResultsGbBuyItem';

export type GETTvTvIdWatchProviders200ResultsGb = {
  link?: string;
  flatrate?: GETTvTvIdWatchProviders200ResultsGbFlatrateItem[];
  buy?: GETTvTvIdWatchProviders200ResultsGbBuyItem[];
};
