/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200CrewItem } from './gETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200CrewItem';
import type { GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200GuestStarsItem } from './gETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200GuestStarsItem';
import type { ImagePath } from './imagePath';

export type GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200 = {
  air_date?: string;
  crew?: GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200CrewItem[];
  episode_number?: number;
  guest_stars?: GETTvTvIdSeasonSeasonNumberEpisodeEpisodeNumber200GuestStarsItem[];
  name?: string;
  overview?: string;
  id?: number;
  production_code?: string | null;
  season_number?: number;
  still_path?: ImagePath;
  vote_average?: number;
  vote_count?: number;
};
