/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdWatchProviders200ResultsDkBuyItem } from './gETTvTvIdWatchProviders200ResultsDkBuyItem';
import type { GETTvTvIdWatchProviders200ResultsDkFlatrateItem } from './gETTvTvIdWatchProviders200ResultsDkFlatrateItem';

export type GETTvTvIdWatchProviders200ResultsDk = {
  link?: string;
  buy?: GETTvTvIdWatchProviders200ResultsDkBuyItem[];
  flatrate?: GETTvTvIdWatchProviders200ResultsDkFlatrateItem[];
};
