/*
 * Generated by orval v5.5.3 🍺
 * Do not edit manually.
 * API
 * ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. # Title
No Description
 * OpenAPI spec version: 3
 */
import type { GETTvTvIdSeasonSeasonNumber200EpisodesItem } from './gETTvTvIdSeasonSeasonNumber200EpisodesItem';
import type { ImagePath } from './imagePath';

export type GETTvTvIdSeasonSeasonNumber200 = {
  _id?: string;
  air_date?: string;
  episodes?: GETTvTvIdSeasonSeasonNumber200EpisodesItem[];
  name?: string;
  overview?: string;
  id?: number;
  poster_path?: ImagePath;
  season_number?: number;
};
